services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/deepakkumar365/n8n_projects.git
    region: singapore  # or oregon/frankfurt, depending on your location
    branch: main
    plan: free  # or starter/standard if needed
    dockerfilePath: Dockerfile
    autoDeploy: true

    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-4oec.onrender.com
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: NODE_ENV
        value: production
